version: '3.8'

services:
    app:
        ports:
            - "8000:80"
        depends_on:
            - database
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - .:/var/www/html
        env_file:
            - .env
    database:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3312:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
    adminer:
        image: adminer
        restart: always
        ports:
            - "8085:8080"

volumes:
    mysql:
